apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
    - cidr: 10.244.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      disabled: false
    - cidr: fd00:10:244::/64
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      disabled: false

