apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sonarqube       # Specify the namespace
  labels:
    app: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432           # PostgreSQL port inside cluster
      targetPort: 5432     # Port on the Pod
      nodePort: 30007      # NodePort for external access (30000-32767)

