apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sonarqube       # Namespace for the deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest       # Latest PostgreSQL image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin             # Hardcoded username
            - name: POSTGRES_PASSWORD
              value: admin@123         # Hardcoded password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim

