apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  type: LoadBalancer       # Permanent external access
  selector:
    app: sonarqube
  ports:
    - name: sonar
      port: 80             # External port
      targetPort: 9000     # Pod container port
      protocol: TCP

